.TH INTERNSCTL 1 "January 2024" "v0.1.0" "internsctl manual"

.SH NAME
internsctl \- Custom Linux command for operations

.SH SYNOPSIS
\fBinternsctl\fR [\fB\-\-help\fR] [\fB\-\-version\fR]

.SH DESCRIPTION
This is a custom Linux command for handling operations.

.SH OPTIONS
\fB\-\-help\fR
       Display help and usage guidelines.

\fB\-\-version\fR
       Display the version of internsctl.

.SH AUTHOR
Rohith Onepice!

.SH SEE ALSO
More information can be found at https://yourdocumentationlink.com
